# Generated by Django 3.0.7 on 2020-07-02 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_auto_20200625_1341'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='category',
            field=models.CharField(choices=[('Travel diaries', 'pending'), ('Achievement', 'Out of delivery'), ('college', 'others')], max_length=200, null=True),
        ),
    ]
