# Generated by Django 3.0.7 on 2020-07-02 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_auto_20200702_1602'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='category',
            field=models.CharField(choices=[('Travel diaries', 'Travel diaries'), ('Achievement', 'Achievement'), ('college', 'college'), ('others', 'others')], max_length=200, null=True),
        ),
    ]
